### ISSUE TITLE
Python 3.6.8 can't start properly 

### ISSUE THREAD

**Issue by sugarp0pe** [sandialabs/dr_robot#41]
Hi, 
Had some wierd erorrs, please help
Ubuntu 18.04.1 fully up to date
Python 3.6.8
<summary>
ubuntu@ubuntu:~/Projects/dr_robot$ pipenv install && pipenv shell
Installing dependencies from Pipfile.lock (9fd82d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 32/32 — 00:00:09
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Launching subshell in virtual environment…
ubuntu@ubuntu:~/Projects/dr_robot$  . /home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/bin/activate
(dr_robot) ubuntu@ubuntu:~/Projects/dr_robot$ dr
driverless  drrobot     
(dr_robot) ubuntu@ubuntu:~/Projects/dr_robot$ drrobot --help
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/bin/drrobot", line 11, in <module>
    load_entry_point('drrobot', 'console_scripts', 'drrobot')()
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/Projects/dr_robot/src/robot_api/cli.py", line 13, in <module>
    from robot_api.robot import Robot
  File "/home/ubuntu/Projects/dr_robot/src/robot_api/robot.py", line 27, in <module>
    from robot_api.api import Ansible, Docker, Aggregation
  File "/home/ubuntu/Projects/dr_robot/src/robot_api/api/__init__.py", line 4, in <module>
    from robot_api.api.upload import Forum, Mattermost, Slack
  File "/home/ubuntu/Projects/dr_robot/src/robot_api/api/upload.py", line 15, in <module>
    import slack
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/slack/__init__.py", line 4, in <module>
    from slack.web.client import WebClient  # noqa
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/slack/web/client.py", line 9, in <module>
    from slack.web.base_client import BaseClient, SlackResponse
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/slack/web/base_client.py", line 15, in <module>
    import aiohttp
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/aiohttp/client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import HeadersParser as HeadersParser
  File "/home/ubuntu.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/home/ubuntu/.local/share/virtualenvs/dr_robot-wkMS6zjP/lib/python3.6/site-packages/aiohttp/helpers.py", line 58, in <module>
    import idna_ssl
ModuleNotFoundError: No module named 'idna_ssl'
</summary>

**Comment by CrimsonK1ng** [comment]
Hi, can you try running ```pip install idna_ssl``` from within your Pipenv shell (or Pipenv install idna_ssl). Then rerun ```drrobot```. That should resolve it. I will update the requirements and Pipfile with the appropriate package for python 3.6,

Please let me know if the error persists.

**Comment by sugarp0pe** [comment]
Hi, thank you for your help, now it all works fine!
Great project!

**Comment by CrimsonK1ng** [comment]
Awesome! Thanks for creating the issue!
